### PR TITLE
feat(rules) add modifiers for the lowercase rule

### PR DESCRIPTION
**Pull request by smakinson**
Adds modifiers to the lowercase validation rule:
* allow_non_alpha (allows numbers & the regex from the existing symbols)
* allow_numeric (allows numbers)
* allow_numeric_dashes (allows numbers and dashes)

Also update the messaging in the en locale for lowercase. Running tests locally passed.

### CODE REVIEW

**Comment by justin-schroeder** [comment]
@smakinson this is excellent. Do you think you could add a few unit tests for this? The test file/block for this rule is already setup here: 

https://github.com/smakinson/formkit/blob/feature/lowercase-mods/packages/rules/__tests__/lowercase.spec.ts

To run your tests just make sure everything is installed at the root (we use pnpm) and run a build `pnpm build` then `pnpm test` ❤️

**Comment by smakinson** [comment]
@justin-schroeder Thanks. Ya I'll add them. Sorry about that. It may be a bit though (time, need more of it, as I'm sure we all do)

**Comment by smakinson** [comment]
@justin-schroeder I added a few tests. Does that fit the requirement?

**Comment by justin-schroeder** [comment]
Excellent! Thank you @smakinson

**Pull request merged**
