### PR TITLE
Adding UnoCSS to themes

### PR DESCRIPTION
**Pull request by GustavoFenilli**
Adding UnoCSS to themes and fixing dependencies for themes.

### CODE REVIEW

**Comment by andrew-boyd** [comment]
Looks great @GustavoFenilli! Thank you!

**Comment by csakis** [comment]
@GustavoFenilli  I'm getting conflicting peer dependencies for @formkit/themes@1.0.0 for unocss:
```
npm ERR! While resolving: @formkit/themes@1.0.0
npm ERR! Found: unocss@0.55.7
npm ERR! node_modules/unocss
npm ERR!   dev unocss@"^0.55.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional unocss@"^0.31.0" from @formkit/themes@1.0.0
npm ERR! node_modules/@formkit/themes
npm ERR!   @formkit/themes@"^1.0.0" from the root project
npm ERR!   @formkit/themes@"1.0.0" from @formkit/vue@1.0.0
npm ERR!   node_modules/@formkit/vue
npm ERR!     @formkit/vue@"^1.0.0" from the root project
npm ERR!     1 more (@sfxcode/formkit-primevue)
npm ERR!
npm ERR! Conflicting peer dependency: unocss@0.31.17
npm ERR! node_modules/unocss
npm ERR!   peerOptional unocss@"^0.31.0" from @formkit/themes@1.0.0
npm ERR!   node_modules/@formkit/themes
npm ERR!     @formkit/themes@"^1.0.0" from the root project
npm ERR!     @formkit/themes@"1.0.0" from @formkit/vue@1.0.0
npm ERR!     node_modules/@formkit/vue
npm ERR!       @formkit/vue@"^1.0.0" from the root project
npm ERR!       1 more (@sfxcode/formkit-primevue)
```

**Comment by GustavoFenilli** [comment]
Does `formkit-primevue` also have a peerDependency of unocss? not sure why the conflict tho.

**Comment by csakis** [comment]
Yes it does. Currently, it needs  `"unocss": "^0.55.4",`

**Pull request merged**
