### PR TITLE
Feature/icons rework

### PR DESCRIPTION
**Pull request by andrew-boyd**
This is a fairly substantial re-do on the icon system. The goal is for using the default FormKit icons to feel like a zero-config option when authoring your forms — while being flexible enough to allow developers to integrate their own icon systems without much headache.

Notable changes:
- Moves plugin to the `@formkit/themes` package as `createThemePlugin`
- `createThemePlugin` is now part of `defaultConfig`
-  Themes can be added via import, or by supplying a `theme` argument to the FormKit config. If the theme does not exist locally it will be fetched from jsDeliver and added to the document `head`
- The `@formkit/icons` package now only exports icons and the raw SVG icons are published as part of the build process
- Adds `icon()` as an available section for input definitions
- Creates a system where icons are retrieved from available sources in the following priority order:
    - The relevant icon prop if the value is a literal SVG definition
    - The `iconRegistry`
    - an available `--fk-icon-*` CSS variable
    - the jsDelivr CDN
- `@formkit/core` now exports `FORMKIT_VERSION` which we use to know which version to make CDN requests to for any missing icons.
- Automatically creates `@${sectionKey}-icon-click` event handlers
- adds styles to genesis to account for new icon placements
- `createThemePlugin` accepts an `iconLoader` function that will allow a user to handle how icons are loaded when requests are make. It expects SVG markup returned as a string or a Promise that resolves to a string representation of an SVG.
- Adds a `FormKitIcon` component to `@formkit/vue` to allow icons to be loaded and displayed via the FormKit icon system outside of inputs.

### CODE REVIEW

**Review by justin-schroeder — CHANGES_REQUESTED** [review]
Just a few tiny changes. Looks really really awesome.

**Comment by justin-schroeder** [comment]
@andrew-boyd somehow there are conflicts now?

**Comment by andrew-boyd** [comment]
@justin-schroeder Good to merge?

**Comment by justin-schroeder** [comment]
do it

**Pull request merged**
