### PR TITLE
fix: useInput.ts accepts kebab-case

### PR DESCRIPTION
**Pull request by CavalcanteLeo**

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Hey @CavalcanteLeo — happy to merge this, can you just add a backing test that shows it working both as `modelValue` and `model-value`? That will ensure we dont have a regression.

**Comment by CavalcanteLeo** [comment]
sure, will do it this weeekend

**Comment by andrew-boyd** [comment]
@CavalcanteLeo I'm going to try to get 0.17.4 released with some other small fixes — Will you have time to add that test so I can merge this in as well?

**Comment by andrew-boyd** [comment]
@CavalcanteLeo I've added a backing test to the `0.17.4` branch and will merge this in.

**Pull request merged**
