### PR TITLE
Adds hasRule utility function

### PR DESCRIPTION
**Pull request by GustavoFenilli**
It check if the rule exists for a set of validations.

### CODE REVIEW

**Comment by GustavoFenilli** [comment]
Sure thing, let me check how to do it and I will write those, also with that in mind, should I also add this to fns to be used like it was described in #233?

**Comment by justin-schroeder** [comment]
I'm not sure I'd add it to `context.fns` since it would then be included in everyone's bundles. With beta.9 we'll be introducing `@formkit/addons` which will allow us to put nice utilities like this into plugins users can choose to install. So we could have one like `addSchemaFns` to add extra functions such as `hasRule` to the `context.fns`

**Comment by GustavoFenilli** [comment]
Added the needed tests for it, let me know if there are missing cases that you see so I can create the missing tests.

**Comment by GustavoFenilli** [comment]
I'm not sure if its useful enough as a convinent way of checking outside a node, or it should be changed to use a node instead of a an arbitrary array and use the parsed rules instead to make this check easier.

**Comment by GustavoFenilli** [comment]
Closing in favor of node.props.parsedRules as it works the same way.

**Pull request closed without merging**
