### PR TITLE
fix(validation): required rule doesn't work as expected

### PR DESCRIPTION
**Pull request by chiquyet199**
This is the fix for this issue: https://github.com/formkit/formkit/issues/452

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Hey — this looks like a good catch/fix. However, the test you added appears to be failing in when I run the tests. Seems like the number rule isn't being run at all?

image

**Comment by chiquyet199** [comment]
@justin-schroeder ok, let me check again, it passed all the tests before I created the PR on my side. Will update the PR soon

**Comment by chiquyet199** [comment]
@justin-schroeder I think we're good now, I have no clue why it failed before but I just deleted the repo and cloned my branch again, all tests passed now. 

Screen Shot 2022-11-02 at 11 14 40 PM

**Comment by chiquyet199** [comment]
@justin-schroeder haha you're welcome, my first PR to an open source 😁

**Pull request merged**
