### PR TITLE
fix: #777 not displaying value on initial state

### PR DESCRIPTION
**Pull request by glennlaysonjr**
- added has value attr to input
- added css to show inhert color

### CODE REVIEW

**Comment by andrew-boyd** [comment]
So looking at this, it'll fix the mask but not the datepicker  — which is hiding the text because of the `opacity` on the `.formkit-overlay`. 

I think the solve for both is actually to get the `formkit-outer` property `data-complete` to equal `true` if the input has a value even if it has not been interacted with.

**Comment by glennlaysonjr** [comment]
I can take a look. Thanks

**Comment by glennlaysonjr** [comment]
@andrew-boyd I updated per your suggestion and tested it fixes the issues. Take a look and let me know. ~ Thanks

**Comment by andrew-boyd** [comment]
Sweet, that seems like a much better solution to me. I'll give it a test and then we'll see if we can get it and some other small items pushed out here soon in another point release.

**Comment by andrew-boyd** [comment]
@glennlaysonjr This is actually even more nuanced — sorry for pointing you in the wrong direction. The `complete` state has dependencies on validation and also on `dirty` — meaning it would only affect inputs that a user has interacted with. 

I've opened a new PR #797 that adds a `emtpy` state that can be checked against and updated the Floating Labels plugin styles to work with that new state.

**Pull request closed without merging**
