### PR TITLE
feat(inputs): improve form to emit success and error events

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
Hey! :)

This PR improves the form `handleSubmit` to emit `submit:success` and `submit:error` events based on the promise of `onSubmit`

### CODE REVIEW

**Comment by andrew-boyd** [comment]
Had a little discussion about this in the office. One issue we see here is that this assumes that the developer's submit handler will produce an uncaught error if it fails — which means in cases where the developer catches and handles an error (hopefully all the time) this would fail to work.

One alternative we could possibly do is store the localStorage cache in memory when the submit hook fires and then offer an extension to the node that would allow you to call something like `node.restoreCache()` in your own submit handler if the submission fails. We'd still be deleting the localStorage cache, but with the opportunity to restore the inputs in the form which would then recreate the cache in localStorage again.

**Comment by JoaoPedroAS51** [comment]
Yes, indeed it would fail if the error was caught. What I do here is catch the error, do what I want to do, then I throw it again, so formkit knows it failed.

But I liked your restore approach. I think it will work great.

**Comment by JoaoPedroAS51** [comment]
@andrew-boyd Should I close here?

**Comment by andrew-boyd** [comment]
@JoaoPedroAS51 Yeah we can close this one. We'll try to get the above discussed update into `0.17.3`. 👍

**Pull request closed without merging**
