### PR TITLE
feat: add typebox validation plugin

### PR DESCRIPTION
**Pull request by crishoj**
I was looking for a [Typebox](https://github.com/sinclairzx81/typebox) equivalent of the [Zod validation plugin](https://formkit.com/plugins/zod), but couldn't immediately find one.

What do you think of this proposal?

It would be useful for [Elysia](https://elysiajs.com) apps.

### CODE REVIEW

**Comment by fenilli** [comment]
It looks good to me, but never used typebox before so can't say for sure.

**Comment by crishoj** [comment]
It's modelled 1:1 like the Zod plugin, based on the question I posed in https://github.com/orgs/formkit/discussions/1349.

Usage:

```ts
import { Type } from '@sinclair/typebox'

const schema = Type.Object({
  message: Type.String({minLength: 10, maxLength: 1000}),
  items: Type.Array(Type.String(), {minItems: 2}),
})

const [typeboxPlugin] = createTypeboxPlugin(schema)
```

And then:

```vue
<FormKit type="form" :plugins="[typeboxPlugin]">
```

**Comment by justin-schroeder** [comment]
@crishoj this seems great to me. Ive merged into release/1.7 which is the next minor version we’ll ship. In the meantime if youd like to write up the documentation for this on a page (similar to zod) we can have that ready to go when this does ship:

https://github.com/formkit/docs-content

**Comment by crishoj** [comment]
Thanks @justin-schroeder, I will write up the documentation.

**Pull request merged**
