### PR TITLE
adds custom attributes and message states by theme

### PR DESCRIPTION
**Pull request by GustavoFenilli**
By adding the theme function from tailwind, it makes it possible to add custom data attributes and message states.

```js
module.exports = {
  ...
  plugins: [
    require('@formkit/tailwindcss')
  ],
  theme: {
    formkit: {
      attributes: ['custom'],
      messageStates: ['success']
    }
  }
}
```

### CODE REVIEW

**Comment by andrew-boyd** [comment]
This looks great @GustavoFenilli! Thanks for taking the time to put it together. I'll get this merged, author a readme for the package, and update the guide to include the `formkit` config property for Tailwind based on this new approach.

**Review by andrew-boyd — COMMENTED** [review]
Will merge after writing / updating some documentation. 👏

**Comment by andrew-boyd** [comment]
@GustavoFenilli let me verify, but I think that our export map takes care of that. When using `require()` it should try to load the `.cjs` file which does have a `module.exports`.

**Comment by GustavoFenilli** [comment]
Closing in favor of adding this PR to the tailwindcss plugin inside @formkit/themes instead.

**Pull request closed without merging**
