### PR TITLE
Fix $formkit shorthand not propagating key

### LINKED ISSUE #232: The `$formkit` schema shorthand does not respect the `key` property
### Reproduction

https://formkit.link/4e82ab9a91528a49f5be4b3f9d19c4c1

### Describe the bug

Vue heavily recycles DOM nodes for efficiency, so when using a schema that swaps elements in the same dom position its important to key each of these. This works when using longhand:

```js
{
  $cmp: 'FormKit',
  props: {
    key: 'my-key'
  }
}
```

But not when using shorthand:

```js
{
  $formkit: 'text',
  key: 'my-key'
}
```

### Environment

All environments

### PR DESCRIPTION
**Pull request by tmm1**
Should fix #232 but I have not been able to confirm yet

### CODE REVIEW

**Comment by tmm1** [comment]
> I have not been able to confirm yet

Figured out how to try it:

`yarn add 'https://gitpkg.now.sh/tmm1/formkit/packages/core?sugar-key-fix'`

However it didn't fix my issue so I guess something is still missing.

**Comment by tmm1** [comment]
I confirmed this works, by running `yarn build` then pointing my app at my patched build using:

```diff
--- a/package.json
+++ b/package.json
@@ -1,5 +1,6 @@
 {
   "dependencies": {
+    "@formkit/core": "../formkit/packages/core",
     "@formkit/themes": "^1.0.0-beta.8",
     "@formkit/vue": "^1.0.0-beta.8",
     "vue": "^3.2.33"

**Comment by tmm1** [comment]
Anything else required to merge this?

**Comment by justin-schroeder** [comment]
Nope! Thanks for the PR — this has been merged into the release/beta.9 branch and published under the `@next` tag on npm

**Pull request merged**
